location = /swagger {
    default_type text/html;
    alias /usr/share/nginx/swagger/index.html;
    include /etc/nginx/includes/security-swagger.conf;
}

location = /swagger/ {
    default_type text/html;
    alias /usr/share/nginx/swagger/index.html;
    include /etc/nginx/includes/security-swagger.conf;
}

location /swagger/auth/ {
    proxy_pass http://auth-api:8080/swagger/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    include /etc/nginx/includes/security-swagger.conf;
}

location /swagger/transactions/ {
    proxy_pass http://transactions-api:8080/swagger/transactions/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    include /etc/nginx/includes/security-swagger.conf;
}

location = /api/auth/login {
    limit_req zone=login burst=8 nodelay;
    proxy_pass http://auth-api:8080/login;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /api/auth/ {
    proxy_pass http://auth-api:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location /api/transactions/ {
    limit_req zone=money burst=40 nodelay;
    proxy_pass http://transactions-api:8080/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
}

location / {
    try_files $uri $uri/ /index.html;
}
