server {
    listen 80;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name _;
    ssl_certificate /etc/letsencrypt/live/vortexbank/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vortexbank/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    root /usr/share/nginx/html;
    index index.html;
    include /etc/nginx/includes/security.conf;
    include /etc/nginx/includes/locations.conf;
}
